apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Release.Name}}-ingress-demo
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /server(/|$)(.*)
            backend:
              serviceName: {{.Release.Name}}-{{.Values.deployments.server}}-service
              servicePort: 80
          - path: /client(/|$)(.*)
            backend:
              serviceName: {{.Release.Name}}-{{.Values.deployments.client}}-service
              servicePort: 80
          - path: /client3(/|$)(.*)
            backend:
              serviceName: {{.Release.Name}}-{{.Values.deployments.client}}-service
              servicePort: 80

