apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    workgroup: client
spec:
  replicas: 2
  selector:
    matchLabels:
      workgroup: client
  template:
    metadata:
      name: client-deployment
      labels:
        workgroup: client
    spec:
      containers:
        - name: server-deployment-container
          image: gcr.io/analytics-team-253708/kubernetes-helm/client
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: domain
              value: client

