apiVersion: apps/v1
kind: Deployment
metadata:
  name: engineering-team
  labels:
    workgroup: engineering-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      team: engineering
  template:
    metadata:
      name: imran-pod
      labels:
        team: engineering
        position: sse
        location: mirpur
    spec:
      containers:
        - name: server-deployment-container
          image: gcr.io/analytics-team-253708/kubernetes-helm/server
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: domain
              value: server

